// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'name': string;
  'pfp': string;
  'role': string;
}
export const cssExports: CssExports;
export default cssExports;
