// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarContainer': string;
  'bubble': string;
  'container': string;
}
export const cssExports: CssExports;
export default cssExports;
