// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'bubble': string;
  'container': string;
  'emojis': string;
}
export const cssExports: CssExports;
export default cssExports;
