// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'emoji': string;
  'emojiFlex': string;
  'emojis': string;
  'preview': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
