// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgImg': string;
  'bgImgOverlay': string;
  'body': string;
  'btn': string;
  'btnIcon': string;
  'btnText': string;
  'btnsContainer': string;
  'container': string;
  'coverContainer': string;
  'descriptionTitle': string;
  'editBtn': string;
  'tag': string;
  'title': string;
  'txtHeader': string;
  'txtHeaderSecLine': string;
  'watchedContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
