// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarContainer': string;
  'headerContainer': string;
  'logo': string;
  'menuItem': string;
  'searchContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
