// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'header': string;
  'itemsCenter': string;
  'itemsContainer': string;
  'libraryAlphaShortcuts': string;
  'libraryContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
