// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'librarySidebarItemContainer': string;
  'librarySidebarItemIcon': string;
  'librarySidebarItemTitle': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
