// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'ldsDualRing': string;
  'loadingText': string;
  'logoIconContainer': string;
  'spinContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
