// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'desc': string;
  'length': string;
  'primaryContainer': string;
  'secOverlay': string;
  'secSubtitle': string;
  'secTitle': string;
  'secondaryContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
