// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'danger': string;
  'none': string;
  'normal': string;
  'success': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
