// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dock': string;
  'dockButtons': string;
  'hiddenUi': string;
  'pointerDetecter': string;
  'progressBar': string;
  'video': string;
  'videoContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
