// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeBtn': string;
  'container': string;
  'currentPfp': string;
  'footer': string;
  'header': string;
  'headerTitle': string;
  'option': string;
  'pfpOptions': string;
  'pfpTab': string;
  'pfpTabs': string;
}
export const cssExports: CssExports;
export default cssExports;
