// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionBtn': string;
  'background': string;
  'closeButton': string;
  'inputContainer': string;
  'inputField': string;
  'inputLabel': string;
  'inputMainContainer': string;
  'joinRoomContainer': string;
  'joinRoomTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
