// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat': string;
  'chatFeed': string;
  'chatbox': string;
  'container': string;
  'content': string;
  'open': string;
  'popout': string;
  'sidebar': string;
  'sidebarContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
