// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat': string;
  'chatBox': string;
  'chatFeed': string;
  'chatInput': string;
  'chatMessages': string;
  'container': string;
  'content': string;
  'emojiSelector': string;
  'open': string;
  'popout': string;
  'roomCode': string;
  'sidebar': string;
  'sidebarContainer': string;
  'sidebarTop': string;
}
export const cssExports: CssExports;
export default cssExports;
