// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'disabled': string;
  'enabled': string;
  'vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
