// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonIcon': string;
  'buttonText': string;
  'buttons': string;
  'container': string;
  'logo': string;
}
export const cssExports: CssExports;
export default cssExports;
