import { app, BrowserWindow, ipcMain, protocol } from 'electron';
import * as fs from "fs";
import * as Path from "path";
import BaseWebsocket from "ws";
import { getMovieMetadata } from "./backend/meta";
import Library, { File } from './backend/library';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const DIRECTORY = Path.resolve("./");

// const library = [
//     "Shrek.mp4",
//     "Shrek 2.mov",
//     "Terminator 2.mp4",
//     "Clutch Powers.mov",
//     "John Wick.mp4",
//     "Batman Ninja.mov",
//     "Guardians of the Galaxy.mp4",
//     "I, Robot.mov",
//     "Snakes on a plane.mp4",
//     "Sharknado.mov",
//     "Army of Darkness.mp4",
//     "Hostel.mov",
//     "The Lego Movie.mp4",
//     "Avatar.mov",
//     "The Amazing Spider-Man.mp4",
//     "Top Gun: Maverick",
//     "Puss In Boots: The Last Wish.mov",
//     "Nope.mp4",
//     "Knives Out.mp4",
//     "Alien.mov",
//     "Robocop.mp4",
//     "Jumanji.mov",
//     "The Conjuring.mp4"
// ];

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let mainWindow: BrowserWindow;
let socket: Websocket;
let socketId = -1;

function newSocket() {
    const newSocketId = Date.now();
    socketId = newSocketId;
    if (socket) socket.close();
    socket = new Websocket("wss://socket.airstrike.tv");
    socket.on("open", () => {
        console.log("websocket open");
        mainWindow.webContents.send("websocket state", {
            connected: true
        });
    });
    socket.once("error", e => {
        console.error(e);
    });

    socket.on("close", () => {
        if (newSocketId != socketId) return console.log("cancelling socket!");
        console.log("websocket close");
        mainWindow.webContents.send("websocket state", {
            connected: false
        });
        newSocket();
    });
}

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true
        },
        autoHideMenuBar: true
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow.maximize();
    
    //input checking
    mainWindow.webContents.on('before-input-event', (event, input) => {
        // FULLSCREEN: Handle the F11 key press.
        if (input.key === 'F10') {
            event.preventDefault();
            mainWindow.setFullScreen(!mainWindow.isFullScreen());
        }

        // DEVTOOLS: Handle the F12 key press.
        if (input.key === 'F12') {
            event.preventDefault();
            mainWindow.webContents.toggleDevTools();
        }

        if (input.key === 'F5') {
            event.preventDefault();
            mainWindow.reload();
        }
    });

    const libraryListener = (files: File[]) => {
        mainWindow.webContents.send("library", files);
    }

    mainWindow.webContents.on('dom-ready', () => {
        mainWindow.webContents.send("emojis", Array.from(emojis.keys()));
        mainWindow.webContents.send("library", Library.get());
        newSocket();
        Library.addListener(libraryListener);
    });

    mainWindow.webContents.on("destroyed", () => {
        console.log("Closing websocket");
        socketId = -1;
        socket.close();
        Library.removeListener(libraryListener);
    });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

app.on('ready', () => {
    ipcMain.on("socket", (e, data) => {

        if (data.type == "leave") {
            socket.runCallback("room ID", null);
        }

        if (data.type == "chat") {
            socket.runCallback("chat", data.data);
        }

        try {
            socket.message(data.type, data.data);
        } catch {}
    });

    ipcMain.on("get metadata", async (e, data) => {
        const meta = await getMovieMetadata(data.filename);
        mainWindow.webContents.send("metadata", {
            filename: data.filename,
            requestId: data.requestId,
            metadata: meta
        });
    });

    createWindow();

    protocol.registerFileProtocol("content", (request, callback) => { // src="content://chungus"
        const contentName = request.url.substring(10);
        if (contentName.includes("..") || contentName.includes(":")) return callback(null);

        const path = Path.join(DIRECTORY, "content", contentName);
        callback({path});
    });

    protocol.registerFileProtocol("avatar", (request, callback) => { // src="avatar://villainbiden"
        const avatarName = request.url.substring(9);
        const avatar = avatars.get(avatarName);
        if (!avatar) return callback(null);

        const path = Path.join(DIRECTORY, "assets", "avatars", avatar);
        callback({path});
    });

    protocol.registerFileProtocol("emoji", (request, callback) => { // src="emoji://joecool"
        const emojiName = request.url.substring(8);
        const emoji = emojis.get(emojiName);
        if (!emoji) return callback(null);

        const path = Path.join(DIRECTORY, "assets", "emojis", emoji);
        callback({path});
    });


});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

if (!fs.existsSync(Path.join(DIRECTORY, "content"))) {
    console.log("making content directory");
    fs.mkdirSync(Path.join(DIRECTORY, "content"));
}

const avatars: Map<string, string> = new Map();
const avatarDir = fs.readdirSync(Path.join(DIRECTORY, "assets", "avatars"));

for (let avatarCategory of avatarDir) {
    if (typeof avatarCategory != "string") continue;
    const avatarCatResults = fs.readdirSync(Path.join("assets", "avatars", avatarCategory));
    for (let avatar of avatarCatResults) {
        if (typeof avatar != "string" || !avatar.includes(".")) continue;
        const extension = Path.extname(avatar).toLowerCase();
        if (!["png", "jpg", "gif"].includes(extension.substring(1))) continue;
        avatars.set(avatar.slice(0, -extension.length), Path.join(avatarCategory, avatar));
    }
}


const emojis: Map<string, string> = new Map();
const emojiDir = fs.readdirSync(Path.join(DIRECTORY, "assets", "emojis"));

for (let emojiCategory of emojiDir) {
    if (typeof emojiCategory != "string") continue;
    const emojiCatResults = fs.readdirSync(Path.join("assets", "emojis", emojiCategory));
    for (let emoji of emojiCatResults) {
        if (typeof emoji != "string" || !emoji.includes(".")) continue;
        const extension = Path.extname(emoji).toLowerCase();
        if (!["png", "jpg", "gif"].includes(extension.substring(1))) continue;
        emojis.set(emoji.slice(0, -extension.length), Path.join(emojiCategory, emoji));
    }
}



class Websocket extends BaseWebsocket {
    private eventListeners: Map<string, ((message: any) => void)[]> = new Map();

    constructor(url: string) {
        super(url);
        this.on("message", message => {
            try {
                const data = JSON.parse(message.toString());
                this.runCallback(data.type, data.data);
            } catch (e) {
                console.error(e);
            }
        });
    }

    runCallback(event: string, data?: any) {
        mainWindow.webContents.send(event, data);
        const listeners = this.eventListeners.get(event) || [];
        for (let callback of listeners) {
            console.log(callback, event, data);
            callback(data);
        }
    }

    addCallback(event: string, callback: (data: any) => void) {
        const listeners = this.eventListeners.get(event);
        if (listeners) {
            listeners.push(callback);
        } else {
            this.eventListeners.set(event, [callback]);
        }
    }

    removeCallback(event: string, callback: (data: any) => void) {
        const listeners = this.eventListeners.get(event);
        if (!listeners) return;
        const index = listeners.indexOf(callback);
        if (index < 0) return;
        listeners.splice(index, 1);
    }

    message(messageType: string, data?: any) {
        this.send(JSON.stringify({
            type: messageType,
            data
        }));
    }
}