import { app, BrowserWindow, ipcMain, protocol } from 'electron';
import * as fs from "fs";
import * as Path from "path";
import BaseWebsocket from "ws";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const DIRECTORY = Path.resolve("./");

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let mainWindow: BrowserWindow;
let socket: Websocket;

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow.maximize();
    
    //input checking
    mainWindow.webContents.on('before-input-event', (event, input) => {
        // FULLSCREEN: Handle the F11 key press.
        if (input.key === 'F10') {
            event.preventDefault();
            mainWindow.setFullScreen(!mainWindow.isFullScreen());
        }

        // DEVTOOLS: Handle the F12 key press.
        if (input.key === 'F12') {
            event.preventDefault();
            mainWindow.webContents.toggleDevTools();
        }

        if (input.key === 'F5') {
            event.preventDefault();
            mainWindow.reload();
        }
    });

    mainWindow.webContents.on('dom-ready', () => {
        console.log("Window opened");
        mainWindow.webContents.send("emojis", Array.from(emojis.keys()));

        socket = new Websocket("wss://airstrike.eyezah.com");
        socket.on("open", () => {
            console.log("websocket open");
            // socket.message("create room");
        });
    });

    mainWindow.webContents.on("destroyed", () => {
        console.log("Closing websocket");
        socket.close();
    });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

app.on('ready', () => {
    ipcMain.on("socket", (e, data) => {

        if (data.type == "leave") {
            socket.runCallback("room ID", null);
        }

        if (data.type == "chat") {
            socket.runCallback("chat", data.data);
        }

        try {
            socket.message(data.type, data.data);
        } catch {}
    });

    createWindow();

    protocol.registerFileProtocol("content", (request, callback) => { // src="content://chungus"
        const contentName = request.url.substring(10);
        if (contentName.includes("..") || contentName.includes(":")) return callback(null);

        const path = Path.join(DIRECTORY, "content", contentName);
        callback({path});
    });

    protocol.registerFileProtocol("avatar", (request, callback) => { // src="avatar://villainbiden"
        const avatarName = request.url.substring(9);
        const avatar = avatars.get(avatarName);
        if (!avatar) return callback(null);

        const path = Path.join(DIRECTORY, "assets", "avatars", avatar);
        callback({path});
    });

    protocol.registerFileProtocol("emoji", (request, callback) => { // src="emoji://joecool"
        const emojiName = request.url.substring(8);
        const emoji = emojis.get(emojiName);
        if (!emoji) return callback(null);

        const path = Path.join(DIRECTORY, "assets", "emojis", emoji);
        callback({path});
    });


});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

if (!fs.existsSync(Path.join(DIRECTORY, "content"))) {
    console.log("making content directory");
    fs.mkdirSync(Path.join(DIRECTORY, "content"));
}

const avatars: Map<string, string> = new Map();
const avatarDir = fs.readdirSync(Path.join(DIRECTORY, "assets", "avatars"));

for (let avatarCategory of avatarDir) {
    if (typeof avatarCategory != "string") continue;
    const avatarCatResults = fs.readdirSync(Path.join("assets", "avatars", avatarCategory));
    for (let avatar of avatarCatResults) {
        if (typeof avatar != "string" || !avatar.includes(".")) continue;
        const extension = Path.extname(avatar).toLowerCase();
        if (!["png", "jpg", "gif"].includes(extension.substring(1))) continue;
        avatars.set(avatar.slice(0, -extension.length), Path.join(avatarCategory, avatar));
    }
}


const emojis: Map<string, string> = new Map();
const emojiDir = fs.readdirSync(Path.join(DIRECTORY, "assets", "emojis"));

for (let emojiCategory of emojiDir) {
    if (typeof emojiCategory != "string") continue;
    const emojiCatResults = fs.readdirSync(Path.join("assets", "emojis", emojiCategory));
    for (let emoji of emojiCatResults) {
        if (typeof emoji != "string" || !emoji.includes(".")) continue;
        const extension = Path.extname(emoji).toLowerCase();
        if (!["png", "jpg", "gif"].includes(extension.substring(1))) continue;
        emojis.set(emoji.slice(0, -extension.length), Path.join(emojiCategory, emoji));
    }
}



class Websocket extends BaseWebsocket {
    private eventListeners: Map<string, ((message: any) => void)[]> = new Map();

    constructor(url: string) {
        super(url);
        this.on("message", message => {
            try {
                const data = JSON.parse(message.toString());
                this.runCallback(data.type, data.data);
            } catch (e) {
                console.error(e);
            }
        });
    }

    runCallback(event: string, data?: any) {
        mainWindow.webContents.send(event, data);
        const listeners = this.eventListeners.get(event) || [];
        for (let callback of listeners) {
            console.log(callback, event, data);
            callback(data);
        }
    }

    addCallback(event: string, callback: (data: any) => void) {
        const listeners = this.eventListeners.get(event);
        if (listeners) {
            listeners.push(callback);
        } else {
            this.eventListeners.set(event, [callback]);
        }
    }

    removeCallback(event: string, callback: (data: any) => void) {
        const listeners = this.eventListeners.get(event);
        if (!listeners) return;
        const index = listeners.indexOf(callback);
        if (index < 0) return;
        listeners.splice(index, 1);
    }

    message(messageType: string, data?: any) {
        this.send(JSON.stringify({
            type: messageType,
            data
        }));
    }
}